# StoryCodeWizard mkdocs Configuration
site_name: StoryCodeWizard Documentation
site_description: CustomTkinter デスクトップアプリケーション - LLMチャット・プロジェクト管理・履歴管理機能を提供
site_author: StoryCodeWizard Team
site_url: https://github.com/your-repo/storycodewizard

# Repository
repo_name: your-repo/storycodewizard
repo_url: https://github.com/your-repo/storycodewizard

theme:
  name: material
  language: ja
  palette:
    # ライトモード
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    # ダークモード
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - toc.integrate

plugins:
  - search:
      lang: ja
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_signature_annotations: true
            show_root_heading: true
            heading_level: 2
            members_order: source
            filters:
              - "!^_"
              - "!^__"
            merge_init_into_class: true

nav:
  - Home: index.md
  - Getting Started:
      - インストール: getting-started/installation.md
      - クイックスタート: getting-started/quickstart.md
      - 基本的な使い方: getting-started/usage.md
  - User Guide:
      - プロジェクト管理: user-guide/project-management.md
      - チャット機能: user-guide/chat-features.md
      - 履歴管理: user-guide/history-management.md
      - UI操作ガイド: user-guide/ui-guide.md
      - Markdown機能: user-guide/markdown-features.md
  - Architecture:
      - システム構成: architecture/system-overview.md
      - UIコンポーネント: architecture/ui-components.md
      - データベース設計: architecture/database.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-repo/storycodewizard
      name: GitHub
    - icon: fontawesome/brands/python
      link: https://www.python.org
      name: Python

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg