name: Deploy MkDocs to GitHub Pages # ワークフロー名をより具体的に変更 (推奨)

on:
  push:
    branches:
      - main # mainブランチへのプッシュ時のみ実行する場合など、適宜変更してください

jobs:
  deploy: # ジョブ名を変更 (推奨)
    runs-on: ubuntu-latest
    permissions: # GITHUB_TOKEN に権限を付与
      contents: write
    steps:
    - uses: actions/checkout@v4 # バージョンを更新
    - name: Set up Python
      uses: actions/setup-python@v5 # バージョンを更新
      with:
        python-version: '3.12'
        cache: 'pip' # pipのキャッシュを有効化 (推奨)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python mkdocs-toc-md
    - name: Build MkDocs site
      run: mkdocs build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4 # バージョンを更新 (v3でも動作しますが最新推奨)
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN を使用
        publish_dir: ./site
        # user_name: 'github-actions[bot]' # コミットユーザー名として推奨
        # user_email: 'github-actions[bot]@users.noreply.github.com' # コミットユーザーメールとして推奨